### ISSUE TITLE
Ethereum Core Developer Meeting 92

### ISSUE THREAD

**Issue by MadeofTin** [ethereum/pm#195]
# Ethereum Core Devs Meeting 92 Agenda

-   Meeting Date/Time:  **Friday 24 July 2020, [14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/14-00)**
-   Meeting Duration 1.5 hours
-   [YouTube Live Stream](https://youtu.be/RWX9vkY7Oas)

# Agenda
1. [Retrospective on call 91](https://ethereum-magicians.org/t/coredevcalls-91-retrospective-how-did-we-do-with-five-why-s/4441)
    - Do you think we need to keep digging into "Why?"
    - Do we want to argue more about some of the answers?
    - Discuss potential solutions based on some of the answers?
3. EIP Discussion
    - [EIP-2565](https://eips.ethereum.org/EIPS/eip-2718)
    -[Type Transcation Envelope](https://eips.ethereum.org/EIPS/eip-2718)
4. How transaction selection happens in a client at the moment
2. Review previous decisions made and action items (if notes available)

Next call: Aug 6th, 2020 14:00 UTC

**Comment by MicahZoltu** [comment]
As always, I can't make the meeting due to Time Zone but I would like to see discussion on getting [Typed Transaction Envelope](https://eips.ethereum.org/EIPS/eip-2718) (2718) included in the next hard fork.  We currently have several EIPs open now that introduce new transaction mechanisms and I think there is significant value in getting 2718 approved for inclusion by the Core Dev teams so we don't have to keep reinventing the wheel for each of these things that want to touch the transaction structure.

It would be *nice* to also see discussion on inclusion of [Sponsored, expiring and batch transactions](https://eips.ethereum.org/EIPS/eip-2711) (2711) as it provides a number of benefits over the current transaction format, but I think this is less critical than 2718.

Finally, if there is time I would also like to see discussion around [Rich Transactions](https://eips.ethereum.org/eip-2803) (2803).  2803 opens up possibilities for new contract design patterns that provide users with better UX and soft-breaks some anti-patterns that are often used (often in ponzi games and scams) (`isHuman` checks).

**Comment by shamatar** [comment]
In a light of recent proposals for much more complex transactions is it possible to discuss how transaction selection happens in a client at the moment? It was mentioned in core devs chat that now it’s largely O(1) (gas price I assume), is it correct?

I’ve mentioned an idea of “flash loan”-like transactions in a chat that would borrow some ETH from miner and then return a borrow after execution, and it would require mining software to relay execution and check for non-commutative behavior. Would it be an interesting direction to think about with potential benefits for end users?

**Comment by MicahZoltu** [comment]
@shamatar It probably would be better to discuss that somewhere other than the Core Dev meeting first to flesh out the idea more.  Usually, things don't reach the core dev call until they are fully fleshed out ideas and there needs to be a decision on whether to implement or not.  Some options for discussion are a GitHub issue here, or ethresear.ch or ethereum-magicians.org.

**Comment by shamatar** [comment]
I’m actually more interested in the generic knowledge if any of node developers thought about it already and if there are fundamental problems with having expensive transaction pre-validation. I can not make any solid proposal or post on ethresearch if e.g. longer validation time will make troubles for miners.

**Comment by MicahZoltu** [comment]
@shamatar What you are describing is exactly what ethresear.ch is for.  😃  You can think of the Core Dev call (which this agenda is for) as the very last step in the process of getting things implemented in Ethereum, and ethresear.ch or ethereum-magicians.org is the first step, when you just have an idea you want to get feedback on.

**Comment by Souptacular** [comment]
Closing in favor of https://github.com/ethereum/pm/issues/196.
