### ISSUE TITLE
EIP-1559 Gas API Call (Breakout #10)

### ISSUE THREAD

**Issue by tvanepps** [ethereum/pm#328]
## Date and Time
Date/Time: Friday, June 4 at 14:00 UTC (10:00 ET)
Duration: 60 mins

## Agenda
- Presentation by Gas API providers
- JSON RPC endpoint for gas price 
    - Addition of `eth_maxPriorityFeePerGas` https://github.com/ethereum/eth1.0-specs/pull/201
    - Need to agree on return value
- JSON RPC endpoint for next block `baseFeePerGas` https://github.com/ethereum/eth1.0-specs/issues/207 
- Open Discussion

⭐ [Cheatsheet: 1559 for Wallets and Users](https://hackmd.io/4YVYKxxvRZGDto7aq7rVkg?view) ⭐

↓ Leave a comment to add anything else ↓

**Comment by timbeiko** [comment]
One thing to discuss is how to update `eth_gasPrice`, quoting from the [R&D discord](https://discord.com/channels/595666850260713488/804019759934078987/847112340280836157): 

> Per the 1559 wallet call, there was a desire for eth_gasPrice to be backwards compatible so initial thought is to add a new optional parameter that signals the caller would like to receive a 1559-style estimate. The alternative is we could add new endpoints eth_maxPriorityFeePerGas and eth_maxFeePerGas that clients can call to get the new info.

**Comment by timbeiko** [comment]
Quick update: as per https://github.com/ethereum/eth1.0-specs/pull/201#issuecomment-852287392, we are likely to add a separate API for the priority fee. It would be good to use the call to discuss what value the API should provide.

**Comment by GregTheGreek** [comment]
@timbeiko do we have a list of different options that it can be calculated so folks can come a bit more prepared? I'm very concerned over the implementations of the GPO so would love to help wallet devs understand what they're getting as a return value!

**Comment by karalabe** [comment]
Geth's implementation currently:

- `eth_gasPrice` **before** London uses the current algorithm (deliberately won't say)
- `eth_gasPrice` **after** London will return the exact same number based on the total fees paid (tip + base)
- `eth_maxPriorityFeePerGas` **after** London will effectively return `eth_gasPrice - baseFee`

Auto-fill details:

- If the user doesn't specify either `gasPrice` or 1559 gas fields, we default to 1559 style transactions
- If the user doesn't specify `maxPriorityFeePerGas`, we default to the above estimation
- If the user doesn't specify `maxFeePerGas`, we default to `maxPriorityFeePerGas + 2*baseFee`

The rationale's behind this thought:

- Users continuing to rely on legacy transactions and `eth_gasPrice` should not observe any behavioral change. (Hence why I didn't detail how the GPO works, it works the same way as until now).
- Users stuffing `eth_gasPrice` into a 1559 tx for the priorityFee or maxFee will be handled gracefully as if they just did a legacy transaction, no shooting yourself in the foot.
- Advanced users who know 1559 is different and how can rely on the new endpoint `eth_maxPriorityFeePerGas` which returns a value for the tip only (thus it won't be mined it used as is without a baseFee + slack on top).

**Comment by barnabemonnot** [comment]
Hi! Yes some thoughts on the proposed oracle:

- I understand the rationale behind picking the three minimum fee transactions, but note that because in 1559 you have a binding basefee, if you want this oracle to be useful during volatile periods, it'd not be great to recommend a price that is unable to be included. This was ok in the current system because even a 2 Gwei transaction among a bunch of 100 Gweis could be included if the miner didn't find anything better, but now with basefee at 100 it's no longer possible. Keep in mind that the 3 minimum price transactions in 1559 will _always_ be something like "what basefee was at that time + the minimum miner fee". So I believe that most of the time, if you are returning eth_gasPrice as the 60th percentile of the series of 3 minimum price transactions over the last X blocks, you'll end up recommending a negative maxPriorityFee when basefee rises (I'll also do a simulation to convince myself), and the opposite problem on the way down. As a thought experiment, suppose you have 20 close to empty blocks in a row (3 transactions each), i.e. basefee is divided by 14. 60th percentile means you'll get the price of the 8th block, which will be roughly the original basefee divided by 3. Let's say the original basefee is 100, so at the 8th block it's 33 and at the 20th block it's 7. Your oracle will now recommend to users a maxPriority fee of 33 - 7 = 26 (!) even though blocks are mostly empty. It's contrived but it's likely the thinking holds to some degree still.

- 20 blocks seems too long, it takes 6 blocks for basefee to double, so 20 blocks is 4 minutes 20 worth of blocks (average) which in worst case leads to basefee 10x'ing. The intuition here is that when basefee stabilises around the current correct market value, instead of catching up to it during spikes, in a way it "cleanses" the environment, you shouldn't need to rely on what happened in the past to determine what you should be doing now. The only periods where you want to use past information to determine your tip would be during spikes, but it's unlikely that we'd ever see a period with 20 full blocks in a row, for reference 6 full blocks means that prices doubled in about 1min20sec. I checked the worst spikes once and even then it wasn't that sudden (lost that analysis to a bad computer crash.... but happy to run it again!). As discussed in the previous point there really is a pretty strong dependency between the length of your look back period and the percentile you choose. You could say "let's keep 20 blocks but up the percentile to 80th" or "let's keep the percentile to 60th and only lookahead 10 blocks", that would probably have about the same effect. But if I had to pick I'd be more inclined to choose the latter because 20 blocks in the past is ancient history in 1559, basefee would have caught up to something by this point.

- In the Discord messages it was discussed that the congestion rate is the important metric, not congestion level. I do think that any 1559-adapted gas price oracles must look at the gas used one way or another. This is the objective source of truth that prices alone cannot capture. If you see a block that is less than full, your oracle should stop advertising higher premiums than necessary. Right now the thinking seems to replicate entirely the current situation (with shorter look back periods) and doesn't take advantage of the fact that block fullness provides the correct measure of congestion rate. I understand the need to not break everything at once and it's something again we could simulate to convince ourselves, but it seems inescapable to me that we cannot be looking only at prices to design a good 1559 oracle.

It all seems to boil down to this: "whereas looking at the minimums ensures we're trying to push prices downward instead of up." What I am arguing for is that it's no longer the role of your gas price oracle to do that :) the binding basefee is constraining enough for users, and will naturally push prices down if they should be lower. So the oracle should either tell users that basefee is caught up and they don't need to worry about it, or that we're currently in a spike and it'd be helpful to know if users are overbidding. Otherwise, reintroducing the subjectivity of prices will naturally bias the correct estimation, which should rely on more objective data points such as the gas used by recent blocks.

**Comment by karalabe** [comment]
I tried to explain conceptually the mechanism, but I guess it got misunderstood somewhere along the way.

Our gas price oracle internally calculates the priority fees paid by the transactions. For the eth_gasPrice call, we will return the estimated priority fee + 1 basefee (which will essentially be the "current" full gasPrice that we estimate pre-London). For eth_maxPriorityFeePerGas, we return the estimated priority fee. The user needs to set the `maxFeePerGas` either manually based on the tip, or Geth defaults to the priority fee + 2x baseFee.

**Comment by fvictorio** [comment]
@karalabe when you say "1 basefee", what value do you use? The base fee of the latest block, the next base fee, or something else?

**Comment by karalabe** [comment]
The current baseFee.

**Comment by danjm** [comment]
Will the call be recorded, or will notes be taken, and made publicly available?

**Comment by zsfelfoldi** [comment]
I wrote a short proposal for a fee suggestion API:
https://gist.github.com/zsfelfoldi/9ca596996f5a556c58dae3aa4f4d0049

**Comment by timbeiko** [comment]
@danjm I don't think we'll have notes, but I'll upload a recording to Youtube.

**Comment by timbeiko** [comment]
Link for the 1559 API wishlist: https://hackmd.io/@timbeiko/1559-api-wishlist

**Comment by Santhosh1692** [comment]
@timbeiko Please notify me once the recording has been uploaded to YouTube. I'll get started by adding the notes.

**Comment by timbeiko** [comment]
Recording available here: https://www.youtube.com/watch?v=SpU6WACP2cM&feature=youtu.be cc: @Santhosh1692
