### ISSUE TITLE
Ethereum Core Devs Meeting 35 Agenda

### ISSUE THREAD

**Issue by chfast** [ethereum/pm#33]
# Ethereum Core Devs Meeting 35 Agenda
### Meeting Date/Time: Friday 03/23/18 at 14:00 UTC (http://www.timebie.com/std/utc.php)
**NOTE: SOME AREAS OF THE WORLD RECENTLY HAD DAYLIGHT SAVINGS TIME**
### [YouTube Live Stream Link](https://www.youtube.com/watch?v=HHK6xhuSyUU)
# Agenda

1. Testing
2. [EIP 712 Discussion](https://github.com/ethereum/pm/issues/33#issuecomment-374174501)
3. EIP process updates.
4. Metropolis.
5. Client/research updates.

Please provide comments to add or correct agenda topics.

**Comment by LefterisJP** [comment]
It would be nice if we could discuss [EIP 712](https://github.com/ethereum/EIPs/pull/712), figure out a proper scope for it,  address the malleability issue and finalize it.

Essentially the discussion has been going on for ages and the scope is in danger of reaching that of [EIP 719](https://github.com/ethereum/EIPs/issues/719). Also a [malleability issue](https://github.com/ethereum/EIPs/pull/712#issuecomment-365413684) was discovered and some solutions were proposed for it.

I would like to see if we could differentiate the two EIPs, keep 712's scope small and see what are the steps to follow towards finalizing it and making sure clients that need to request signing permission implement it.

**Comment by pipermerriam** [comment]
Python Update

- web3 v4 is nearing a stable release.
- first trinity alpha *should* be right around the corner.  We're polishing off a minimal MVP with a limited subset of the light client sync, a limited subset of the JSON-RPC API and the ability to drop into a python REPL with a web3 instance connected to the node.

**Comment by mkalinin** [comment]
Harmony Update
- we did a release with performance improvements and some other fixes ([1.7.0](https://github.com/ethereum/ethereumj/releases/tag/1.7.0)), latest version is here [1.7.1](https://github.com/ethereum/ethereumj/releases/tag/1.7.1)
- there is, also, a good progress in Casper research, currently waiting for updates from pyethapp to adopt them and setup test network from scratch (it fell apart a week ago cause deposit scaling factor became zero)

**Comment by 5chdn** [comment]
Parity Update

- finished integrating the PWasm VM (testing it on Kovan now, hard-fork at block 6600000)
  - this will enable Wasm VM in addition to Ethereum VM
  - WVM and EVM contracts are able to interact
  - there was a talk at EthCC demoing this (unfortunately, unrecorded)
  - tutorials available for Rust -> Wasm contracts at [pwasm-tutorial](https://github.com/paritytech/pwasm-tutorial)
- outsourcing the wallet UI to make space for a light wallet ([github/parity-js](https://github.com/parity-js))
  - parity wallet is now a stand-alone electron wallet
  - the built-in UI is disabled by default (but can still be forced to run)
- light sync now uses a trusted block header RLP to speed things up significantly (PR pending [parity/8075]())
- Whisper is getting a command-line interface (PR pending [parity/8201](https://github.com/paritytech/parity/pull/8201))
- complete overhaul of the transaction queue (PR pending [parity/8074](https://github.com/paritytech/parity/pull/8074))
- refactoring of our engines to allow future PoS implementations (Casper FFG)

**Comment by AlexeyAkhunov** [comment]
Turbo-Geth update:

- implemented hashfile optimisation (hashes of the top 5 levels of the state hex tree in a memory-mapped file): https://medium.com/@akhounov/thank-you-and-current-status-of-turbo-geth-885e6e033b32
- fixed lots of tests, but not finished
- started to test and fix API functionality. First was storageRangeAt(). To make it work, had to further decouple database from the hex tree, so that API works only off the database, without ever building the hex tree
- started to test sync with "normal" memory (4-16 Gb). Found lots of issues and fixing them now.

**Comment by chfast** [comment]
cpp-ethereum update:

- A lot of changes around VM related to EVM-C and eWASM support.
- Database fixes and improvements.
- Network and blockchain sync fixes.
- libscrypt integration via Hunter.

[All merged PRs since last month](https://github.com/ethereum/cpp-ethereum/pulls?page=2&q=is%3Apr+created%3A%3E%3D2018-02-20+is%3Aclosed).

**Comment by chrishobcroft** [comment]
Please can I contact the person who makes the live-stream for this event?

I see you are using YouTube for streaming, I would like to work out how you might be able to use Livepeer, which is an Ethereum-based livestreaming platform.

For more details, see www.livepeer.org or contact me at chris@livepeer.org

**Comment by fulldecent** [comment]
@lrettig @Souptacular Hello, this is regarding your note on EIP-1 / magicians. 

Please quickly share a link if you have more information on the Ethereum Magicians event that happened this week. I believe I am involved with that group but I didn't know of this meeting.

I have come to Dallas for this weekend and will be representing the Magicians at the Explore 721 event to explain what's coming up, give some of my own spin (among other topics).

One of the people reading this message may possibly be attending the Dallas event Saturday (today/tomorrow depending on your timezone). If yes and if you have more information on this please call me, I think you can get my number.

**Comment by lrettig** [comment]
Hi @fulldecent, I think there may have been a miscommunication/misunderstanding here. There was no Fellowship meeting this week. There was an All Core Devs call yesterday (which is what this thread is about). See my reply to your post on the Fellowship forum at https://ethereum-magicians.org/t/impressions-of-the-first-fellowship-meeting/66/5?u=lrettig for more.

**Comment by fulldecent** [comment]
Thank you, much appreciated.

**Comment by emmonspired** [comment]
This issue of signing data in a visible format has already been supported by MetaMask's personal_sign method. I wrote a white paper regarding its usage for authentication and verification of messages with it. https://steemit.com/ethereum/@emmonspired/whitepaper-and-demo-ux-for-authenticated-and-verified-erc20-payments-using-metamask-and-ethsigutil

**Comment by vogelito** [comment]
Hi,

I’m not sure this is the right spot to leave comments, so please point me in the right direction if not. As context, we operate a digital currency exchange that has supported ethereum since early 2016.

I just went through the meeting notes for meeting 35 and have some thoughts:
- first of all, thank you so much for posting these notes. They are incredibly useful
- more frequent/smaller hard forks are probably very nice for a development team, but not as great for the rest of the community. In 2016 when the network was attacked, we really struggled with operations, customer communication, etc... right now ethereum forks are big news so there’s significant exposure, news translation (our customers don’t speak English) and it makes thing easier(ish), having them very frequent would be harder for us
- please please please don’t get rid of the geth console. It’s absolutely processless and incredibly valuable to us

Thanks and keep up the amazing work!

**Comment by 5chdn** [comment]
@vogelito just put it on the #36 agenda.

I have to admit I use the Geth console daily, one thing that bothered me that Parity does not have it ;)
