### ISSUE TITLE
Proposal to Include EIP-4396 in the Shanghai Hard Fork

### ISSUE THREAD

**Issue by adietrichs** [ethereum/pm#406]
I just now [opened the PR](https://github.com/ethereum/EIPs/pull/4396) to create what will presumably become [EIP-4396](https://github.com/quilt/EIPs/blob/time-aware-basefee/EIPS/eip-4396.md).

The EIP proposes accounting for time between blocks in the base fee calculation to target a stable throughput by time, instead of by block. It appears to be desirable to have something like this in place already for the merge, to avoid (or at least greatly reduce) throughput degradation due to missed slots, or even due to potential consensus issues.

To maximize the chance of this EIP being included in the merge fork, the adjustments are kept to a minimum, with more involved changes discussed in the rationale section.

**Comment by Tied2eth** [comment]
Well I would like that
I have had a sha1 embedded I'm my id credentials for at least 4 years. I have yet to verify a address mint a token or use any source code and because it was put there with out my knowledge I have yet to really call a return call but have been shown how much  was out there.  Well I figured a couple hours ago and i got the address indexed true but was not compatible with the sha1 it was indexing for years. And I have so many addresss and wallets iam not sure how consolidate call contracts pools ens names if my not being able to make any successful calls or not able to complete a time agreement or a verified signed one i have spent gas on the same things multiple times I have according to scanners I have token s all over the place pools liquidity tokens mining. Eth2.
So as far as this eip goes my accounts have really have Ben 98% deposit only for the past 4 or 5 years or longer  it would be cool to track retrieve and verify any thing that I could starting with my verified signature that's actually payable
Tied2token.eth 

 that I couldn't or things that dev s had stripped from my wallet s  from my paid  for accounts out of it I can see tokens

**Comment by poojaranjan** [comment]
Breakout-room discussion (EIP-4396 ) 

- [Agenda](https://github.com/ethereum/pm/issues/408)
- [Recording]( https://www.youtube.com/watch?v=ZD8k83Opdww)
- [Summary](https://github.com/ethereum/pm/issues/408#issuecomment-956504559)

**Comment by timbeiko** [comment]
We agreed on ACD126 to not include this in The Merge, but consider it for Shanghai. @adietrichs are you OK if I just change the name of the issue to reference Shanghai instead, so we keep it open, along with the history here?

**Comment by adietrichs** [comment]
@timbeiko did it for you 🙂

**Comment by timbeiko** [comment]
@adietrichs note that on #616 we agreed to use Ethereum Magicians to discuss potential Shanghai EIPs async over the next few weeks. See [here](https://ethereum-magicians.org/t/shanghai-core-eip-consideration/10777/) for more info.

**Comment by timbeiko** [comment]
We finalized the scope for Shanghai on ACD151, and discussions about Cancun inclusion should be moved to https://ethereum-magicians.org/t/cancun-eip-consideration/12060
