### ISSUE TITLE
Eth 1.x Proposal Sync 1 Agenda

### ISSUE THREAD

**Issue by lrettig** [ethereum/pm#65]
# Eth 1.x Proposal Sync 1 Agenda
### Call will not be livestreamed or recorded, but unattributed notes will be published ([Chatham House Rule](https://www.chathamhouse.org/chatham-house-rule)).

# Agenda
1. Transparency, note taking, Chatham House rules
1. Recap of Nov. 2 discussion
1. Simulation working group [proposal](https://docs.google.com/document/d/1pIW6Uac5Qanx_L5Y_G4Ucrx_gjITkBgzQKmlBQbW3Cg/edit)
1. State rent working group [proposal](https://ethereum-magicians.org/t/ethereum-state-rent-for-eth-1-x-pre-eip-document/2018?u=lrettig)
1. Ewasm working group [proposal](https://ethereum-magicians.org/t/ewasm-working-group-proposal-for-eth-1-x/2033?u=lrettig)
1. Chain pruning [proposal](https://gist.github.com/karalabe/60be7bef184c8ec286fc7ee2b35b0b5b)
1. January workshop update (Joseph Chow)
1. Continuation of transparency discussion (if necessary)

**Comment by HershyatHatch** [comment]
@lrettig I asked on twitter, but I will do the old 'double-up' -

What is the thinking behind not recording this call?

**Comment by lrettig** [comment]
> What is the thinking behind not recording this call?

That is my recollection of the consensus in the room when we decided to have this call, that it will be open to core devs only, that it will not be recorded or livestreamed, and that unattributed notes will be taken and shared. This was at the request of several core devs who wanted to feel that they could speak openly.

To be clear, this is not my decision and I have no power to unilaterally change this.

@Souptacular if you (or others) have a different understanding please let me know.

**Comment by lrettig** [comment]
This was discussed among @AlexeyAkhunov, @Souptacular, @karalabe, @gcolvin, @5chdn and others on the core devs call last week. Notes [here](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2050.md). Look for "Hudson: How do we handle the call on the 30th?":

> Hudson:
> For my purposes definition of core devs is working on low-level projects
> There is a grey area including teams such as Infura working on low-level RPC
> For now, meeting on 30th is not closed but may be closed to anyone but core devs
> Notes may or may not be released

**Comment by HershyatHatch** [comment]
So that conversation starts off with Hudson saying.

Hudson: I'm having reservations on how open the meeting on the 30th should be, we said we wanted it to be private, but I think maybe it should be more open. Here are some options..." notes taken, published, livestreamed, etc.


After some further discussion, with no plausible reasons  given for keeping it closed 

(other than Alexy's concern about his research being used in bad faith, which he more recently said that he no longer has concerns about  https://ethereum-magicians.org/t/ethereum-state-rent-for-eth-1-x-pre-eip-document/2018/6?u=hershy)

Greg and Alexy said this:

Greg: Once there are meetings across groups, it shouldn't be secret
Press will report whatever they can find, it won't be complete or accurate

Alexey: If no one else is arguing for it to be closed, let's make it open

After a little more discussion, Hudson sums up thusly:

Hudson: For now, meeting on 30th is not closed but may be closed to anyone but core devs
Notes may or may not be released


So, the consensus in the room, absolutely was not that the call should be closed. The conversation ends with a "for now it is open" (with the both-sides-of-the-fence caveat that it "may be closed".)

**Comment by HershyatHatch** [comment]
And @lrettig I appreciate that this wasn't your decision, nor is it your call to unilaterally change it. I'm really just inquiring as to the process of all this and hoping to get some light shine on that, if possible.

**Comment by lrettig** [comment]
@HershyatHatch You're asking important questions and I appreciate that. I'm all for shining light :)

@Souptacular said multiple times on the call last week that the meeting would be open only to core devs and researchers ("open" here means open to the usual attendees of the all core devs meetings, i.e., "core devs" somewhat loosely and subjectively defined), that it would not be livestreamed/recorded, and that notes will be taken and may or may not be shared.

I intend to respect his wishes, but I will bring this topic up at the start of the call for brief discussion to ensure we have consensus on this point.

**Comment by lrettig** [comment]
Confirmed with @Souptacular that we intend to publish unattributed notes.

**Comment by karalabe** [comment]
Chain pruning proposal https://gist.github.com/karalabe/60be7bef184c8ec286fc7ee2b35b0b5b

**Comment by lrettig** [comment]
Notes are up at https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Eth1x%20Sync%201.md. Closing.
