### ISSUE TITLE
(e)PBS Breakout Room

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#953]
### Meeting Info
* [Feb 13, 2024, 14:00-15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240213T140000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
* Recording: https://youtu.be/63juNVzd1P4
* [Ethereum Protocol Calls Calendar subscription](https://calendar.google.com/calendar/u/0?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Agenda

* (e)PBS design discussion tradeoffs 
    * please add links/pre-reads in the comments!

**Comment by terencechain** [comment]
Dropping some links here: 

[Beacon chain spec](https://github.com/potuz/consensus-specs/blob/f31929acd92efea3d3ac92ce7a8c6ea05bb2472c/specs/_features/epbs/beacon-chain.md)
[Fork choice spec](https://github.com/potuz/consensus-specs/blob/f31929acd92efea3d3ac92ce7a8c6ea05bb2472c/specs/_features/epbs/fork-choice.md)
[General design notes](https://github.com/potuz/consensus-specs/blob/f31929acd92efea3d3ac92ce7a8c6ea05bb2472c/specs/_features/epbs/design.md)
[Networking spec](https://github.com/terencechain/consensus-specs/blob/6913f0d2bc116cb69420fb058e53e0da7c0cc03c/specs/_features/ePBS/p2p-interface.md)
[Validator spec](https://github.com/terencechain/consensus-specs/blob/6913f0d2bc116cb69420fb058e53e0da7c0cc03c/specs/_features/ePBS/validator.md)
[Builder spec](https://github.com/terencechain/consensus-specs/blob/6913f0d2bc116cb69420fb058e53e0da7c0cc03c/specs/_features/ePBS/builder.md)

I'm working on consolidating them into a general outline doc. Will have more to share in the coming days

**Comment by michaelneuder** [comment]
heyo! highlighting a few extra docs:

[*Relays in a post-ePBS world*](https://ethresear.ch/t/relays-in-a-post-epbs-world/16278) – highlights the "bypassability" ideas.
[*Proposer-initiated splitting*](https://ethresear.ch/t/payload-timeliness-committee-ptc-an-epbs-design/16054#proposer-initiated-splitting-18)  – discusses (in my view) the biggest issue with ePBS constructions.
[*Consider the ePBS*](https://notes.ethereum.org/@mikeneuder/consider-the-epbs) – outlines why i don't think the Feb 6 incident should change the perspective on ePBS.

I am also hoping to write a short doc on "ePBS with builder collateral" to share my perspective on that version of the design! for extra links on ePBS, see: https://notes.ethereum.org/@mikeneuder/infinite-buffet. 

hope this helps!

**Comment by ralexstokes** [comment]
my goal for this call is to get everyone on the same page around the state of ePBS r&d and hopefully reach consensus on plausibility for pectra (which kind of started this whole arc).

I think having a call around state of R&D is _super_ valuable and my personal opinion is that ePBS is not ready for pectra (although happy to be convinced otherwise :) ). that being said, calls like this are a great way to accelerate the R&D so that we can compress shipping timelines on ePBS generally

here's my suggested agenda:

* stokes gives overview of mev-boost today and why we want to enshrine PBS
  * auction for builders to buy blockspace from proposers
  * need trusted intermediary: relay
    * brokers exchange to ensure:
    * payload validity
    * and auction payment
  * relays are single points of failure, targets for implementation of censorship, also big funding question
  * remove the relay by enshrining its functions into the protocol
    * builders and proposers can use gossip infra to coordinate
    * use protocol to enforce payment
  * still, questions…
    * is the payload valid and on time? => PTC
    * “splitting” attacks to grief builder
    * gossip better than point-to-point comms?
    * do builders pay JIT or is collateral locked?
* potuz, terence, (and others?) have been working on an ePBS flavor
  * state of research & implementation
  * key resource: https://ethresear.ch/t/minimal-epbs-beacon-chain-changes/18653
* open questions / discussion

**Comment by djrtwo** [comment]
Thanks @ralexstokes!

My general thoughts were:

* highlight designs (and as you note, the current "design" is extra-protocol)
* in doing so — highlight unknowns, tough design decisions, non-optimalities that exists. As well as to ground everyone in rough engineering complexity
* This should help next steps:
    * Are we at the point to transition out of R&D and into concrete specs and semi-production development [regardless of the target fork]
    * and if not, what is the path to get there, who needs to be involved, etc
